name: Automation Tests

on:
  push:
    branches:
      - main
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '25'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: maven-${{ hashFiles('**/pom.xml') }}

      - name: Install dependencies
        run: mvn clean install -DskipTests

      - name: Run tests
        run: mvn test

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: testng-report
          path: target/surfire-reports/

      - name: Upload screenshots
        uses: actions/upload-artifact@v4
        with:
          name: screenshots
          path: screenshots/